### ISSUE TITLE
Error: Could not get Google Bard.

### ISSUE THREAD

**Issue by alokid** [EvanZhouDev/bard-ai#31]
Error: Could not get Google Bard.
    at Module.init (file:///c:/alok/node_modules/bard-ai/index.js:29:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hamz (c:\alok\connect\hamz.js:2467:1)

**Comment by EvanZhouDev** [comment]
Please provide more information, or a [MRE](https://stackoverflow.com/help/minimal-reproducible-example)—it works on my end.

Ensure that you can you Bard normally, and you are using the __Secure-1PSID cookie exactly.

**Comment by neelhabib** [comment]
`import Bard from "bard-ai";

async function brd() {
  await Bard.init(
    "YghfQJmM7w64HSzihRMOO6efTY_br9PCcOoL6E9tsTJ1OIuK_NRSeBb_sgTXIxpLeQ."
  );
  console.log(await askAI("who are you"));
}
brd();
`

this is my code. getting the same error.

**Comment by alokid** [comment]
> ```
> 
> 
> async function brd() {
>   await Bard.init(
>     "YghfQJmM7w64HSzihRMOO6efTY_br9PCcOoL6E9tsTJ1OIuK_NRSeBb_sgTXIxpLeQ."
>   );
>   console.log(await askAI("who are you"));
> }
> brd();
> ```
> 
> this is my code. getting the same error.

My code is also the same, as above. experiencing an error

Error: Could not get Google Bard.
    at Module.init (file:///c:/alok/node_modules/bard-ai/index.js:29:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async brd (c:\alok\connect\hamz.js:2577:3) Promise {
  <rejected> Error: Could not get Google Bard.
      at Module.init (file:///c:/alok/node_modules/bard-ai/index.js:29:16)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async brd (c:\alok\connect\hamz.js:2577:3)
}
Unhandled Rejection at: Promise {
  <rejected> Error: Could not get Google Bard.
      at Module.init (file:///c:/alok/node_modules/bard-ai/index.js:29:16)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async brd (c:\alok\connect\hamz.js:2577:3)
} reason: Error: Could not get Google Bard.
    at Module.init (file:///c:/alok/node_modules/bard-ai/index.js:29:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async brd (c:\alok\connect\hamz.js:2577:3)
Error: Could not get Google Bard.
    at Module.init (file:///c:/alok/node_modules/bard-ai/index.js:29:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async brd (c:\alok\connect\hamz.js:2577:3) Promise {
  <rejected> Error: Could not get Google Bard.
      at Module.init (file:///c:/alok/node_modules/bard-ai/index.js:29:16)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async brd (c:\alok\connect\hamz.js:2577:3)
}

**Comment by alokid** [comment]
![image](https://github.com/EvanZhouDev/bard-ai/assets/138843462/aef6f07e-c6bf-4967-bc59-5e0039dd3fe5)

**Comment by EvanZhouDev** [comment]
Try clearing cookies on bard.google.com, log in, and copy the new key.

**Comment by alokid** [comment]
> Try clearing cookies on bard.google.com, log in, and copy the new key.

work, thank you so many good people for making the bard-ai module.

**Comment by neelhabib** [comment]
> Try clearing cookies on bard.google.com, log in, and copy the new key.

ok. now its working.

**Comment by ThatXliner** [comment]
@EvanZhouDev Maybe add this to an FAQ section on the docs

**Comment by EvanZhouDev** [comment]
Yep! All v2 things I'm working on.

**Comment by Jucamhc** [comment]
I should continue doing it in javascript, do you know when it's ready or what I should modify

**Comment by ThatXliner** [comment]
> Try clearing cookies on bard.google.com, log in, and copy the new key.

@Jucamhc
