### ISSUE TITLE
🐛 [BUG]: TypeError: Cannot read properties of null (reading '4')

### ISSUE THREAD

**Issue by eliiran1231** [EvanZhouDev/bard-ai#60]
### Prerequisites

- [X] I have searched the [issues](https://github.com/EvanZhouDev/bard-ai/issues) and believe that it has not already been reported
- [X] It occurs on the latest version of `bard-ai`
- [X] I have read the [FAQ](https://bard-ai.js.org/faq/) and there are no solutions there

### Bug Description

sometimes i get this error while talking to bard, after some digging, turns out that the variable chatData is null sometimes due to a problem in the parsing from json. here is the full error:

`TypeError: Cannot read properties of null (reading '4')
    at #query (file:///C:/Users/mma91/OneDrive/%D7%A9%D7%95%D7%9C%D7%97%D7%9F%20%D7%94%D7%A2%D7%91%D7%95%D7%93%D7%94/milki/node_modules/bard-ai/index.js:240:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Chat.ask (file:///C:/Users/mma91/OneDrive/%D7%A9%D7%95%D7%9C%D7%97%D7%9F%20%D7%94%D7%A2%D7%91%D7%95%D7%93%D7%94/milki/node_modules/bard-ai/index.js:353:32)
    at async bardAI (file:///C:/Users/mma91/OneDrive/%D7%A9%D7%95%D7%9C%D7%97%D7%9F%20%D7%94%D7%A2%D7%91%D7%95%D7%93%D7%94/milki/index.js:53:22)
    at async file:///C:/Users/mma91/OneDrive/%D7%A9%D7%95%D7%9C%D7%97%D7%9F%20%D7%94%D7%A2%D7%91%D7%95%D7%93%D7%94/milki/index.js:115:32`

### Reproduction Steps

talk to bard for a while, i did notice it tends happen more in the evening

### Occurance Rate

I can reproduce this bug 60% of the time.

**Comment by ThatXliner** [comment]
Possible duplicate of #53

**Comment by eliiran1231** [comment]
> Possible duplicate of #53

bard is available in my country and i use the latest verison

**Comment by EvanZhouDev** [comment]
Are you using the __Secure-1PSIDTS cookie as well? See docs here: https://bard-ai.js.org/faq/#cant-use-bard

**Comment by izhekka** [comment]
I'm using both `__Secure-1PSID` and `__Secure-1PSIDTS` and face the same issue occasionally.
Refreshing the `__Secure-1PSIDTS` cookie solves the issue.
