### ISSUE TITLE
ISSUE FROM NODE.JS

### ISSUE THREAD

**Issue by Helohhhh** [EvanZhouDev/bard-ai#62]
Sorry, but i am just starting to code in Javascript. I get this error while using the command` '''node script.js'''` and i get this error:
 ```
import Bard, { askAI } from "bard-ai";
^^^^^^

SyntaxError: Cannot use import statement outside a module
←[90m    at Module._compile (internal/modules/cjs/loader.js:892:18)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:812:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:724:14)←[39m
←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)←[39m
←[90m    at internal/main/run_main_module.js:17:11←[3
```
It would be great if you help me

**Comment by ThatXliner** [comment]
rename it to `script.mjs`

**Comment by EvanZhouDev** [comment]
Or just set `type: "module"` in package.json :)

**Comment by ThatXliner** [comment]
https://nodejs.org/api/esm.html#enabling
